disabled_rules:
  - force_cast
  - function_body_length
  - large_tuple
  - operator_whitespace
  - todo
  - trailing_comma

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 100
    error: 100
